// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngkrscfufadtafvanwlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5na3JzY2Z1ZmFkdGFmdmFud2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDc1OTksImV4cCI6MjA3MTYyMzU5OX0.U57hmzudvqU_WCAlG88pWv0ufBleQ2P8HLd7olQe3m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});